// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StreamForge.Playback.Api.Data;

#nullable disable

namespace StreamForge.Playback.Api.Migrations
{
    [DbContext(typeof(PlaybackDbContext))]
    partial class PlaybackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("playback")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StreamForge.Playback.Api.Data.ConsumedMessage", b =>
                {
                    b.Property<string>("Topic")
                        .HasMaxLength(249)
                        .HasColumnType("character varying(249)")
                        .HasColumnName("topic");

                    b.Property<int>("Partition")
                        .HasColumnType("integer")
                        .HasColumnName("partition");

                    b.Property<long>("Offset")
                        .HasColumnType("bigint")
                        .HasColumnName("offset");

                    b.Property<DateTimeOffset>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("RejectionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rejection_code");

                    b.HasKey("Topic", "Partition", "Offset");

                    b.HasIndex("EventId");

                    b.ToTable("consumed_messages", "playback");
                });

            modelBuilder.Entity("StreamForge.Playback.Api.Data.PlaybackPackage", b =>
                {
                    b.Property<Guid>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.Property<string>("AssetPrefix")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("asset_prefix");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("bucket");

                    b.Property<string>("MasterPlaylistEtag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("master_playlist_etag");

                    b.Property<string>("MasterPlaylistObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("master_playlist_object_key");

                    b.Property<DateTimeOffset>("ProjectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("projected_at_utc");

                    b.HasKey("VideoId");

                    b.ToTable("packages", "playback");
                });

            modelBuilder.Entity("StreamForge.Playback.Api.Data.PlaybackVariant", b =>
                {
                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.Property<string>("Tier")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tier");

                    b.Property<long>("BandwidthBitsPerSecond")
                        .HasColumnType("bigint")
                        .HasColumnName("bandwidth_bits_per_second");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("PlaylistEtag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("playlist_etag");

                    b.Property<string>("PlaylistObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("playlist_object_key");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("VideoId", "Tier");

                    b.ToTable("variants", "playback");
                });

            modelBuilder.Entity("StreamForge.Playback.Api.Data.PlaybackVariant", b =>
                {
                    b.HasOne("StreamForge.Playback.Api.Data.PlaybackPackage", "Package")
                        .WithMany("Variants")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("StreamForge.Playback.Api.Data.PlaybackPackage", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
