// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StreamForge.Feed.Api.Data;

#nullable disable

namespace StreamForge.Feed.Api.Migrations
{
    [DbContext(typeof(FeedDbContext))]
    [Migration("20260903164254_AddHlsAvailability")]
    partial class AddHlsAvailability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("feed")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StreamForge.Feed.Api.Data.Entities.ConsumedKafkaMessage", b =>
                {
                    b.Property<string>("Topic")
                        .HasMaxLength(249)
                        .HasColumnType("character varying(249)")
                        .HasColumnName("topic");

                    b.Property<int>("Partition")
                        .HasColumnType("integer")
                        .HasColumnName("partition");

                    b.Property<long>("Offset")
                        .HasColumnType("bigint")
                        .HasColumnName("offset");

                    b.Property<DateTimeOffset>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("RejectionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rejection_code");

                    b.HasKey("Topic", "Partition", "Offset")
                        .HasName("pk_consumed_messages");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_consumed_messages_event_id");

                    b.ToTable("consumed_messages", "feed");
                });

            modelBuilder.Entity("StreamForge.Feed.Api.Data.Entities.FeedRendition", b =>
                {
                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.Property<string>("Tier")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tier");

                    b.Property<string>("AudioCodec")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("audio_codec");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("bucket");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("Etag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("etag");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("object_key");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("VideoCodec")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("video_codec");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("VideoId", "Tier")
                        .HasName("pk_renditions");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ux_renditions_object_key");

                    b.ToTable("renditions", "feed");
                });

            modelBuilder.Entity("StreamForge.Feed.Api.Data.Entities.FeedVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<bool>("HasCompletion")
                        .HasColumnType("boolean")
                        .HasColumnName("has_completion");

                    b.Property<bool>("HasHls")
                        .HasColumnType("boolean")
                        .HasColumnName("has_hls");

                    b.Property<bool>("HasMetadata")
                        .HasColumnType("boolean")
                        .HasColumnName("has_metadata");

                    b.PrimitiveCollection<string[]>("Hashtags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("hashtags");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("SortKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sort_key");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateTimeOffset?>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_videos");

                    b.HasIndex("SortKey")
                        .IsUnique()
                        .HasDatabaseName("ux_videos_sort_key");

                    b.HasIndex("HasMetadata", "HasCompletion", "SortKey")
                        .HasDatabaseName("ix_videos_ready_feed");

                    b.ToTable("videos", "feed");
                });

            modelBuilder.Entity("StreamForge.Feed.Api.Data.Entities.FeedRendition", b =>
                {
                    b.HasOne("StreamForge.Feed.Api.Data.Entities.FeedVideo", "Video")
                        .WithMany("Renditions")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_renditions_videos");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamForge.Feed.Api.Data.Entities.FeedVideo", b =>
                {
                    b.Navigation("Renditions");
                });
#pragma warning restore 612, 618
        }
    }
}
