using Microsoft.AspNetCore.Diagnostics.HealthChecks;using Microsoft.EntityFrameworkCore;using Microsoft.Extensions.Diagnostics.HealthChecks;using StreamForge.Playback.Api.Data;using StreamForge.Playback.Api.Options;using StreamForge.Playback.Api.Services;
var builder=WebApplication.CreateBuilder(args);builder.Services.AddControllers();builder.Services.AddProblemDetails();
builder.Services.AddOptions<KafkaOptions>().BindConfiguration(KafkaOptions.SectionName).Validate(x=>!string.IsNullOrWhiteSpace(x.BootstrapServers)&&!string.IsNullOrWhiteSpace(x.ConsumerGroupId)&&!string.IsNullOrWhiteSpace(x.CompletedTopic)).ValidateOnStart();
builder.Services.AddOptions<StorageOptions>().BindConfiguration(StorageOptions.SectionName).Validate(x=>!string.IsNullOrWhiteSpace(x.Endpoint)&&!string.IsNullOrWhiteSpace(x.PublicEndpoint)&&!string.IsNullOrWhiteSpace(x.AccessKey)&&!string.IsNullOrWhiteSpace(x.SecretKey)).ValidateOnStart();
builder.Services.AddOptions<PlaybackOptions>().BindConfiguration(PlaybackOptions.SectionName).Validate(x=>x.SignedUrlExpirySeconds==3600,"Playback signatures must be one hour.").ValidateOnStart();
var connection=builder.Configuration.GetConnectionString("PlaybackDatabase")??throw new InvalidOperationException("PlaybackDatabase is required.");builder.Services.AddDbContextFactory<PlaybackDbContext>(o=>o.UseNpgsql(connection,n=>n.MigrationsHistoryTable("__ef_migrations_history",PlaybackDbContext.Schema)));
builder.Services.AddSingleton(TimeProvider.System);builder.Services.AddSingleton<IManifestStorage,ManifestStorage>();builder.Services.AddSingleton<ManifestRewriter>();builder.Services.AddSingleton<PlaybackTelemetry>();builder.Services.AddScoped<CompletionProjector>();builder.Services.AddHostedService<KafkaConsumerService>();
builder.Services.AddHealthChecks().AddCheck("self",()=>HealthCheckResult.Healthy(),tags:["live"]).AddCheck<PlaybackDatabaseHealthCheck>("postgresql",tags:["ready"]).AddCheck<PlaybackStorageHealthCheck>("minio",tags:["ready"]).AddCheck<PlaybackKafkaHealthCheck>("kafka",tags:["ready"]);
var app=builder.Build();using(var scope=app.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<PlaybackDbContext>();await db.Database.MigrateAsync();await scope.ServiceProvider.GetRequiredService<IManifestStorage>().VerifyAsync(CancellationToken.None);}app.MapControllers();app.MapHealthChecks("/health/live",new HealthCheckOptions{Predicate=x=>x.Tags.Contains("live")});app.MapHealthChecks("/health/ready",new HealthCheckOptions{Predicate=x=>x.Tags.Contains("ready")});app.MapHealthChecks("/health");app.Run();public partial class Program;
