// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StreamForge.Engagement.Api.Data;

#nullable disable

namespace StreamForge.Engagement.Api.Migrations
{
    [DbContext(typeof(EngagementDbContext))]
    [Migration("20260906102100_InitialEngagement")]
    partial class InitialEngagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("engagement")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StreamForge.Engagement.Api.Data.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("VideoId", "CreatedAtUtc", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_comments_video_created");

                    b.ToTable("comments", "engagement");
                });

            modelBuilder.Entity("StreamForge.Engagement.Api.Data.Entities.ConsumedKafkaMessage", b =>
                {
                    b.Property<string>("Topic")
                        .HasMaxLength(249)
                        .HasColumnType("character varying(249)")
                        .HasColumnName("topic");

                    b.Property<int>("Partition")
                        .HasColumnType("integer")
                        .HasColumnName("partition");

                    b.Property<long>("Offset")
                        .HasColumnType("bigint")
                        .HasColumnName("offset");

                    b.Property<DateTimeOffset>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("RejectionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rejection_code");

                    b.HasKey("Topic", "Partition", "Offset")
                        .HasName("pk_consumed_messages");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_consumed_messages_event_id");

                    b.ToTable("consumed_messages", "engagement");
                });

            modelBuilder.Entity("StreamForge.Engagement.Api.Data.Entities.KnownVideo", b =>
                {
                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at_utc");

                    b.HasKey("VideoId")
                        .HasName("pk_videos");

                    b.ToTable("videos", "engagement");
                });

            modelBuilder.Entity("StreamForge.Engagement.Api.Data.Entities.Reaction", b =>
                {
                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("SourceOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("source_offset");

                    b.Property<int>("SourcePartition")
                        .HasColumnType("integer")
                        .HasColumnName("source_partition");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("value");

                    b.HasKey("VideoId", "UserId")
                        .HasName("pk_reactions");

                    b.ToTable("reactions", "engagement", t =>
                        {
                            t.HasCheckConstraint("ck_reactions_value", "value IN ('like', 'dislike')");
                        });
                });

            modelBuilder.Entity("StreamForge.Engagement.Api.Data.Entities.VideoView", b =>
                {
                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.Property<long>("Count")
                        .HasColumnType("bigint")
                        .HasColumnName("count");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("VideoId")
                        .HasName("pk_video_views");

                    b.ToTable("video_views", "engagement", t =>
                        {
                            t.HasCheckConstraint("ck_video_views_count", "count >= 0");
                        });
                });

            modelBuilder.Entity("StreamForge.Engagement.Api.Data.Entities.Comment", b =>
                {
                    b.HasOne("StreamForge.Engagement.Api.Data.Entities.KnownVideo", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_videos");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamForge.Engagement.Api.Data.Entities.Reaction", b =>
                {
                    b.HasOne("StreamForge.Engagement.Api.Data.Entities.KnownVideo", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reactions_videos");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamForge.Engagement.Api.Data.Entities.VideoView", b =>
                {
                    b.HasOne("StreamForge.Engagement.Api.Data.Entities.KnownVideo", "Video")
                        .WithOne()
                        .HasForeignKey("StreamForge.Engagement.Api.Data.Entities.VideoView", "VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_video_views_videos");

                    b.Navigation("Video");
                });
#pragma warning restore 612, 618
        }
    }
}
